version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  target-branch: master
  labels:
  - dependencies
  commit-message:
    prefix: chore
    include: scope
